<?php

use Drupal\Core\Form\FormStateInterface;

/**
* {@inheritdoc}
*/
function custom_inline_edit_theme($existing, $type, $theme, $path) {
  return [
    'custom_inline_edit_form' => [
      'variables' => [
        'entity_id' => NULL,
        'field' => NULL,
        'value' => NULL,
        'output' => NULL,
        'edit_form' => NULL,
      ],
      'template' => 'custom_inline_edit_form'
    ]
  ];
}


function custom_inline_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {

}



